### ISSUE TITLE
Are you planning to update this package regularly?

### ISSUE THREAD

**Issue by frabrunelle** [chuikoffru/meteor-bootstrap-4-scss#1]
Hey! Thank you for making this package :smile: 

I am building a new app right now and I decided to use Bootstrap v4 even though it's still in alpha. I made a few tests and it seems stable enough for me.

I was wondering if you were planning to update this package from time to time?

I could also probably help you by making pull requests. Or if you prefer I can start my own package and update it regularly.

Cheers.

**Comment by sebakerckhof** [comment]
What does this package do differently from the official one? (since twbs:bootstrap@4.0.0-alpha also is available since 25/08)?

**Comment by frabrunelle** [comment]
@sebakerckhof Yes, but this package includes the scss files instead of css so it's easier to customize.

but yeah, I'll just use `twbs:bootstrap@4.0.0-alpha` for now :)
